import colors from 'vuetify/lib/util/colors'
export default {
  // global theme for the app
  globalTheme: 'light', // light | dark

  // dark theme colors
  dark: {
    text_light: '#fff',
    nav: '#3c3f41',
    chips: '#272C32',
    appbar: '#101419',
    background: '#943886',
    surface: '#3c3f41',
    primary: '#0096c7',
    secondary: '#5c7f94',
    accent: '#59bbbb',
    error: '#FF5252',
    info: '#2196f3',
    warning: '#FFC107',

    success: '#00d27a',
    green_bg: '#002a18',
    red_bg: '#45111a',
    blue_bg: '#09192e',
    green: '#03C077',
    green_c1: '#21ca88',
    green_c2: '#52d6a3',
    green_c3: '#82e3be',
    green_c4: '#b1f6dc',
    green_o1: '#03a768',
    green_o2: '#027549',
    green_dark2: '#027549',
    green_o3: '#01482c',
    green_o4: '#003e26',
    green_dark_grey: '#60776f',
    green_grey: '#60776f',

    blue: colors.blue.base,
    blue_a1: colors.blue.darken3,
    blue_c1: colors.blue.lighten1,
    blue_c2: colors.blue.lighten2,
    blue_c3: colors.blue.lighten3,
    blue_c4: colors.blue.lighten4,
    blue_o1: colors.blue.darken1,
    blue_o2: colors.blue.darken2,
    blue_o3: colors.blue.darken3,
    blue_o4: colors.blue.darken4,

    red: colors.red.base,
    red_c1: colors.red.lighten1,
    red_c2: colors.red.lighten2,
    red_c3: colors.red.lighten3,
    red_c4: colors.red.lighten4,
    red_o1: colors.red.darken1,
    red_o2: colors.red.darken2,
    red_o3: colors.red.darken3,
    red_o4: colors.red.darken4,
    grey_ll1_dd2: colors.grey.darken2,
    grey_c1: colors.grey.lighten1,
    grey_c2: colors.grey.lighten2,
    grey_c3: colors.grey.lighten3,
    grey_c4: colors.grey.lighten4,

    grey_o1: colors.grey.darken1,
    grey_o2: colors.grey.darken2,
    grey_o3: colors.grey.darken3,
    grey_o4: colors.grey.darken4,

    orange_c3: colors.orange.lighten2

  },

  // light theme colors
  light: {
    text_light: '#000000',
    nav: '#ffffff',
    chips: '#dbe0e6',
    background: '#ffffff',
    surface: '#f2f5f8',
    primary: '#0096c7',
    secondary: '#2a4f66',
    accent: '#59bbbb',
    error: '#ef476f',
    info: '#2196F3',
    warning: '#ffd166',
    success: '#00d27a',
    green_bg: '#ccf6e4',
    red_bg: '#fad7dd',
    blue_bg: '#d5e5fa',
    green: '#03C077',
    green_o1: '#21ca88',
    green_o2: '#52d6a3',
    green_o3: '#82e3be',
    green_o4: '#b1f6dc',
    green_c1: '#03a768',
    green_c2: '#027549',
    green_dark2: '#027549',
    green_c3: '#01482c',
    green_c4: '#003e26',
    green_dark_grey: '#60776f',
    green_grey: '#169a6c',

    blue: colors.blue.base,
    blue_a1: colors.blue.darken1,
    blue_o1: colors.blue.lighten1,
    blue_o2: colors.blue.lighten2,
    blue_o3: colors.blue.lighten3,
    blue_o4: colors.blue.lighten4,
    blue_c1: colors.blue.darken1,
    blue_c2: colors.blue.darken2,
    blue_c3: colors.blue.darken3,
    blue_c4: colors.blue.darken4,

    red: colors.red.base,
    red_o1: colors.red.lighten1,
    red_o2: colors.red.lighten2,
    red_o3: colors.red.lighten3,
    red_o4: colors.red.lighten4,
    red_c1: colors.red.darken1,
    red_c2: colors.red.darken2,
    red_c3: colors.red.darken3,
    red_c4: colors.red.darken4,

    grey_ll1_dd2: colors.grey.lighten1,
    grey_o1: colors.grey.lighten1,
    grey_o2: colors.grey.lighten2,
    grey_o3: colors.grey.lighten3,
    grey_o4: colors.grey.lighten4,
    grey_c1: colors.grey.darken1,
    grey_c2: colors.grey.darken2,
    grey_c3: colors.grey.darken3,
    grey_c4: colors.grey.darken4,

    orange_c3: colors.orange.darken3
  }
}
