resources:
  App\Entity\Chart\ChartLayout:
    attributes:
      security: 'is_granted("ROLE_USER")'
      pagination_items_per_page: 25
      normalization_context:
        skip_null_values: false
        groups: ['crud']
      denormalization_context:
        groups: ['crud']
