resources:
  App\Entity\ResetPassword:
    properties:
      token:
        identifier: true
    collectionOperations:
      post:
        path: /reset-password/request
        method: 'POST'
        controller: App\Controller\ResetPasswordController::request
        validation_groups: ['request']
        normalization_context:
          groups: [ ]
        denormalization_context:
          groups: [ 'write-request' ]
      validate:
        path: /reset-password/validate
        method: 'POST'
        controller: App\Controller\ResetPasswordController::validate
        validation_groups: ['validate']
        normalization_context:
          groups: [ ]
        denormalization_context:
          groups: [ 'write-validate' ]
      reset:
        path: /reset-password/reset
        method: 'POST'
        controller: App\Controller\ResetPasswordController::reset
        validation_groups: ['reset']
        normalization_context:
          groups: [ ]
        denormalization_context:
          groups: [ 'write-reset' ]
    itemOperations:
      get:
        method: 'GET'
    attributes:
      pagination_items_per_page: 25
      normalization_context:
        skip_null_values: false
        groups: ['admin-read']
      denormalization_context:
        groups: ['write-reset', 'write-validate','write-request' ]
