<?php

namespace App\Controller\Admin;

use Dentiman\ScheduleBundle\Entity\ScheduleLog;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class ScheduleLogCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return ScheduleLog::class;
    }

    public function configureActions(Actions $actions): Actions
    {
        $actions->disable( Action::DELETE,Action::EDIT,Action::NEW)
            ->add(Crud::PAGE_INDEX, Action::DETAIL)
        ;
        return parent::configureActions($actions); // TODO: Change the autogenerated stub
    }

    public function configureCrud(Crud $crud): Crud
    {
        $crud->setDefaultSort(['finishedAt' =>'DESC']);
        return parent::configureCrud($crud);
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            AssociationField::new('schedule'),
            TextField::new('message'),
            DateTimeField::new('finishedAt'),
        ];
    }

}
